openapi: '3.0.0'
info:
  title: User Api
  description: User Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: User
paths:
  /api/v1/user:
    get:
      summary: method for find users
      operationId: findUsers
      tags:
        - User
      parameters:
        - in: query
          name: userParams
          allowEmptyValue: true
          schema:
            $ref: '#/components/schemas/FindUserRequest'
      responses:
        200:
          description: found users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
    post:
      summary: create User
      operationId: createUser
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        201:
          description: Created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    FindUserRequest:
      type: object
      description: user Request parameters
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        phone:
          type: string
    UserResponse:
      type: object
      description: User Response DTO
      properties:
        name:
          type: string
        phone:
          type: string
    UserCreateRequest:
      type: object
      description: User dto
      properties:
        name:
          type: string
        phone:
          type: string




